\connect product_service_db product_service_user
-- Create the 'category' table
CREATE TABLE category (
                          category_id SERIAL PRIMARY KEY,
                          category_name VARCHAR(255) UNIQUE NOT NULL,
                          image_url VARCHAR(255)
);

-- Create the 'product' table
CREATE TABLE product (
                         product_id BIGSERIAL PRIMARY KEY,
                         product_name VARCHAR(255) NOT NULL,
                         image_url VARCHAR(255) NOT NULL,
                         price_unit DOUBLE PRECISION NOT NULL,
                         sku VARCHAR(100) UNIQUE NOT NULL,
                         quantity INTEGER NOT NULL CHECK (quantity >= 0),
                         created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                         category_id INTEGER NOT NULL REFERENCES category(category_id),
                         vendor_id BIGINT NOT NULL,
                         description TEXT,
                         rating DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                         review_count INTEGER NOT NULL DEFAULT 0
);
-- Indexes
CREATE INDEX idx_product_category_id ON product(category_id);

-- Insert sample categories
INSERT INTO category (category_name, image_url)
VALUES
    ('laptop', 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'),
    ('book', 'https://i.tribune.com.pk/media/images/506375-Books-1360705862/506375-Books-1360705862.JPG'),
    ('phone', 'https://static.esrgear.com/blog/wp-content/uploads/2020/07/shutterstock_663569995.jpg');


-- Insert sample products
-- INSERT INTO product (product_name, image_url, price_unit, sku, quantity, category_id, vendor_id)
-- VALUES
--     ('Iphone X', 'https://cdn2.cellphones.com.vn/x/media/catalog/product/x/-/x-2_1_4.jpg', 209.99, 'SKU12345', 50, 3, 2),
--     ('Laptop', 'http://example.com/images/laptop.jpg', 1299.99, 'SKU12346', 30, 1, 2),
--     ('Novel Book', 'http://example.com/images/book.jpg', 19.99, 'SKU12347', 100, 2, 2);

-- Insert additional sample products for 'Laptop' category (category_id = 1)
INSERT INTO product (product_name, image_url, price_unit, sku, quantity, category_id, vendor_id,description)
VALUES
    ('Acer Aspire 5 laptop', 'https://nguyengialaptop.com/wp-content/uploads/2023/02/Acer-Aspire-5-A515-2.jpg', 599.99, 'SKU12348', 25, 1, 3,'Upgraded Seal is just opened for upgrade only, we can provide 1-years warraty on Upgraded RAM/SSD as a seller and original 1-Year Manufacture warranty on remaining components. The latest 11th Gen Core i5-1135G7 processor, 2.4GHz, 4Cores. The new Intel Iris Xe Graphics provides performance and crisp, stunning visuals –with the convenience of a thin & light laptop.\n8GB DDR4, 512GB M.2 NVMe PCIe SSD.\n14.0" Full HD LED display (1920 x 1080). Experience crisp, lifelike colors and sharp details.You also have more space to work with thanks to narrow bezels. More intense shades and distinctions are possible with Acer Color Intelligence.\nStayed connected to IEEE 802.11ac, WiFi6 and Bluetooth, other ports include 1xHDMI, 2xUSB 3.2 Gen 1 Type-A, 1xUSB 3.2 Gen 1 Type-C, 3xUSB Ports.\nOperating System: Windows 11 Home. Bundle with EAT mouse.'),
    ('Acer Predator Helios 300 laptop', 'https://laptoptld.com/wp-content/uploads/2022/05/Laptop-Acer-Predator-Helios-300-COREI7-4-1.jpg', 1199.99, 'SKU12349', 15, 1, 3,'15.6" Full HD (1920 x 1080) Widescreen LED-backlit IPS display (144Hz Refresh Rate, 3ms Overdrive Response Time, 300nit Brightness & 72% NTSC), 12th Generation Intel Core i7-12700H 6-Core Processor\n512GB NVMe SSD, 16 GB DDR4 2933MHz Dual-Channel Memory\nNVIDIA GeForce RTX 3060 GPU with 6GB of dedicated GDDR6 VRAM, 4-Zone RGB Backlit Keyboard\nWireless: Killer Double Shot Pro Wireless-AX 1650i 802. 11ax Wi-Fi 6; LAN: Killer Ethernet E2600 10/100/1000 Gigabit Ethernet LAN, DTS X: Ultra-Audio; 4th Gen All-Metal AeroBlade 3D Fan\nConnectivity technology: Bluetooth, Windows 11 Home'),
    ('Acer Swift 3 laptop', 'https://cdn2.cellphones.com.vn/x/media/catalog/product/t/e/text_ng_n_6__119_2.png', 749.99, 'SKU12350', 20, 1, 3,'Powerful Productivity: AMD Ryzen 7 5700U Octa-Core Processor with Radeon Graphics run your most demanding apps with lightning-fast responsiveness and hyper-efficient battery usage to keep you productive and entertained all day\nVery Visual: Immerse yourself in consistently rich and bright visuals on the 14" Full HD widescreen LED-backlit 100% sRGB display with 85.73% screen-to-body, 16:9 aspect ratio and narrow bezels\nInternal Specifications: 8GB LPDDR4X on-board memory; 512GB NVMe solid-state drive storage to store your files and media\nWindows Hello with Fingerprint Reader: Biometric fingerprint reader and Windows Hello sign-in options help keep your Acer PC secure\nConnections: 802.11ax Wi-Fi 6 Dual-Band 2.4GHz and 5GHz featuring MU-MIMO technology; Bluetooth 5.2\nAcer''s Purified.Voice technology, features enhanced digital signal processing to cancel out background noise, improve speech accuracy and far-field pickup, which not only makes calls clearer, but makes talking to Alexa easier than before.\nUsing Alexa on your PC is as easy as asking a question. Just ask and Alexa can check your calendar, create lists, play music, answer questions, read the news and more.'),
    ('Asus ZenBook 13 laptop', 'https://phucanhcdn.com/media/product/44367_zenbook_flip_13_oled_ux363_grey_h1.jpg', 799.99, 'SKU12351', 30, 1, 3,'The world''s thinnest ultraportable OLED laptop — 2.2 lb and 0.46”\nNew AI-powered Intel Core Ultra series — Intel Core Ultra 7 Processor 155U 1.7 GHz (12MB Cache, up to 4.8 GHz, 12 cores, 14 Threads) and Intel Graphics. With 1TB SSD storage and 32GB LPDDR5x RAM, explore with more speed, more seamlessly.\nCircular design — Thoughtfully made with up to 90% PIR, PCR, ocean-bound recycled materials and fortified with our revolutionary Plasma Ceramic Aluminum matte finish. Certified EPEAT Gold with Climate+.\nWindows Copilot AI key — Meet Copilot in Windows – your AI-powered assistant for quick answers, creative inspiration, and focused tasks. Boost productivity with fast answers, image generation, and more.\nASUS Lumina OLED display — Immerse yourself in unparalleled visuals with the Zenbook S 13''s 16:10 touch displays boasting a 2880 x 1800 resolution, vibrant 400-nit HDR peak brightness, smooth 60Hz refresh rate, and Pantone validated 100% DCI-P3 color accuracy.\nSound by Harmon / Kardon with Dolby Atmos — super linear speakers are 2x louder boosted with surround sound.\nMilitary-grade durability — Meeting US MIL-STD 810H military standards*, the Zenbook S 13 ensures unmatched reliability in harsh conditions. Rigorous testing enhances longevity, guaranteeing that your laptop is ready for work, travel, or relaxation both today and in the future.'),
    ('Asus ROG Strix G15 laptop', 'https://laptopfull.com/library/module_new/asus-rog-strix-g15-g513ih-hn015w--xam-_s2665.jpg', 1299.99, 'SKU12352', 10, 1, 3,'POWER THROUGH ANYTHING – Powered by Windows 11, an AMD Ryzen 7 6800HS processor, and NVIDIA GeForce RTX 3050 Laptop GPU at 95W Max TGP, the G15 allows you to handle even the most demanding games with ease.\nBLAZING FAST MEMORY AND STORAGE – Multitask swiftly with 8GB of DDR5-4800MHz memory and speed up loading times with 512GB of PCIe 4x4.\nLIGHTNING FAST, CRYSTAL CLEAR DISPLAY – You can’t beat the enemy if you don’t see them coming. The G15 features a fast FHD 144Hz panel and Adaptive-Sync for a stellar gaming and viewing experience.\nROG INTELLIGENT COOLING – To put this amount of power in a gaming laptop, you need an even better cooling solution. The G15 features liquid metal on the CPU among other premium features, to allow for better sustained performance over long gaming sessions.\nMORE FPS WITH MUX SWITCH - A MUX Switch increases laptop gaming performance by routing frames directly to the display bypassing the iGPU.\nXBOX GAME PASS ULTIMATE – Get a free 90-day pass and gain access to over 100 high-quality games. With games added all the time, there’s always something new to play.'),
    ('Asus VivoBook 15 laptop', 'https://cdn.ankhang.vn/media/product/24158_asus_vivobook_15_x1504za_nj517w__.jpg', 649.99, 'SKU12353', 35, 1, 3,'Aspect Ratio:16:9\n15.6 inch Full HD (1920x1080) 4-way NanoEdge bezel display with a stunning 88% screen-to-body ratio\nCompatible with Google Classroom; run Google Classroom on Microsoft Edge or Internet Explorer 11\nLatest 10th Gen Intel Core i3-1005G1 CPU (4M Cache, up to 3.4 GHz)\n8 GB DDR4 RAM and 128 GB PCIe NVMe M.2 SSD\nErgonomic backlit keyboard with fingerprint sensor activated via Windows Hello\nExclusive Ergolift design for an improved typing position\nComprehensive connections including USB 3.2 Type-C, USB 3.2 Type-A, USB 2.0, and HDMI; Gigabit Wi-Fi 5 (802.11ac) (USB Transfer speed may vary. Learn more at ASUS website)\nWindows 10 in S mode exclusively runs apps from the Microsoft Store. To install an app that isn''t available in the Microsoft Store, simply switch out of S mode in three easy steps. There''s no charge to switch out of S mode'),
    ('Apple MacBook Air M1 2020 laptop', 'https://cdn.tgdd.vn/Files/2023/03/07/1515322/chip-m1-h2-080323-230836.jpg', 999.99, 'SKU12354', 40, 1, 3,'All-Day Battery Life – Go longer than ever with up to 18 hours of battery life.\nPowerful Performance – Take on everything from professional-quality editing to action-packed gaming with ease. The Apple M1 chip with an 8-core CPU delivers up to 3.5x faster performance than the previous generation while using way less power.\nSuperfast Memory – 8GB of unified memory makes your entire system speedy and responsive. That way it can support tasks like memory-hogging multitab browsing and opening a huge graphic file quickly and easily.\nStunning Display – With a 13.3 inch Retina display, images come alive with new levels of realism. Text is sharp and clear, and colors are more vibrant.\nWhy Mac – Easy to learn. Easy to set up. Astoundingly powerful. Intuitive. Packed with apps to use right out of the box. Mac is designed to let you work, play, and create like never before.\nSimply Compatible – All your existing apps work, including Adobe Creative Cloud, Microsoft 365, and Google Drive. Plus you can use your favorite iPhone and iPad apps directly on macOS. Altogether you’ll have access to the biggest collection of apps ever for Mac. All available on the App Store.\nEasy to Learn – If you already have an iPhone, MacBook Air feels familiar from the moment you turn it on. And it works perfectly with all your Apple devices. Use your iPad to extend the workspace of your Mac, answer texts and phone calls directly on your Mac, and more.\nFanless Design – Your MacBook Air stays cool and runs quietly even while tackling intense workloads.\nAppleCare – Every Mac comes with a one-year limited warranty and up to 90 days of complimentary technical support. Get AppleCare plus to extend your coverage and reduce the stress and cost of unexpected repairs.\nEnvironmentally Friendly – MacBook Air is made with a 100 percent recycled aluminum enclosure and uses less energy for a smaller carbon footprint.'),
    ('Apple MacBook Pro 14 2023 laptop', 'https://cdn.tgdd.vn/Files/2021/10/17/1390997/17_1280x720-800-resize.jpg', 1999.99, 'SKU12355', 20, 1, 3,'SUPERCHARGED BY M3 — With an 8-core CPU and 10-core GPU, the Apple M3 chip can help you blaze through everyday multitasking and take on pro projects like editing thousands of photos or 4K video.\nBUILT FOR APPLE INTELLIGENCE — Apple Intelligence helps you write, express yourself, and get things done effortlessly. It draws on your personal context while setting a brand-new standard for privacy in AI. Coming in beta this fall.\nUP TO 22 HOURS OF BATTERY LIFE — Go all day thanks to the power-efficient design of Apple silicon. The MacBook Pro laptop delivers the same exceptional performance whether it’s running on battery or plugged in. (Battery life varies by use and configuration. See apple.com/batteries for more information.)\nBRILLIANT PRO DISPLAY — The 14.2-inch Liquid Retina XDR display features Extreme Dynamic Range, 1000 nits of sustained brightness for stunning HDR content, up to 600 nits of brightness for SDR content, and pro reference modes for doing your best work on the go. (The display has rounded corners at the top. (Measured diagonally, the screen is 14.2 inches. Actual viewable area is less.)\nFULLY COMPATIBLE — All your pro apps run lightning fast — including Adobe Creative Cloud, Apple Xcode, Microsoft 365, Medivis SurgicalAR, and many of your favorite iPhone and iPad apps. And with macOS, work and play on your Mac are even more powerful. Elevate your presence on video calls. Access information in all-new ways. And discover even more ways to personalize your Mac.\nADVANCED CAMERA AND AUDIO — Look sharp and sound great with a 1080p FaceTime HD camera, a studio-quality three-mic array, and a six-speaker sound system with Spatial Audio.\nCONNECT IT ALL — This MacBook Pro features a MagSafe charging port, two Thunderbolt / USB 4 ports, an SDXC card slot, an HDMI port, and a headphone jack. Enjoy fast wireless connectivity with Wi-Fi 6E (in countries and regions where 6E is supported) and Bluetooth 5.3. Supports one external display.\nADVANCED SECURITY — Every Mac comes with industry‑leading encryption, robust virus protections, and a powerful firewall system. And free security updates help keep your Mac protected.\nWORKS WITH ALL YOUR APPLE DEVICES — You can do amazing things when you use your Apple devices together. Copy something on iPhone and paste it on MacBook Pro. Use your MacBook Pro to answer FaceTime calls or send texts with Messages. And that’s just the beginning.\nBUILT TO LAST — The all-aluminum unibody enclosure is exceptionally durable. Free software updates keep things running smoothly for years to come.'),
    ('Apple MacBook Pro 16 2019 laptop', 'https://i.ytimg.com/vi/hQ5CrCFFKK8/maxresdefault.jpg', 2499.99, 'SKU12356', 15, 1, 3,'Ninth-generation 6-Core Intel Core i7 Processor\nStunning 16-inch Retina Display with True Tone technology\nTouch Bar and Touch ID\nAmd Radeon Pro 5300M Graphics with GDDR6 memory\nUltrafast SSD'),
    ('Apple MacBook Air M2 2023 laptop', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlUnt4DMnvI_zwgQAraaMjk-IYifzOc1xreyVkRZL_6DGKI9XhtPaIJQdEz3s6_Id-t-s&usqp=CAU', 1099.99, 'SKU12357', 35, 1, 3,'IMPRESSIVELY BIG, IMPOSSIBLY THIN — The 15-inch MacBook Air makes room for more of what you love with a spacious Liquid Retina display. The durable 100 percent recycled aluminum enclosure is strikingly thin and light.\nSUPERCHARGED BY M2 — Get more done faster with a powerful 8-core CPU, 10-core GPU, and up to 24GB of unified memory.\nUP TO 18 HOURS OF BATTERY LIFE — Go all day with the power-efficient performance of the Apple M2 chip. (Battery life varies by use and configuration. See apple.com/batteries for more information.)\nSPACIOUS, BEAUTIFUL DISPLAY — The high-resolution, 15.3-inch Liquid Retina display features 500 nits of brightness, P3 wide color, and support for one billion colors for vibrant images and incredible detail. (The display on the 15-inch MacBook Air has rounded corners at the top. When measured as a standard rectangular shape, the screen is 15.3 inches diagonally; actual viewable area is less.)\nSILENT DESIGN — MacBook Air features a fanless design that runs completely silent, no matter the task.\nSIMPLY COMPATIBLE — With thousands of apps optimized for Apple silicon, all your favorites are lightning fast in macOS, including Microsoft Excel and PowerPoint, Adobe Creative Cloud, and Google Workspace. And free software updates keep things running smoothly and securely. (Apps are available on the App Store. Title availability is subject to change.)\nADVANCED CAMERA AND AUDIO — Look sharp and sound great with a 1080p FaceTime HD camera and three-mic array. Immerse yourself in movies and music with a six-speaker sound system and Spatial Audio.\nMAGIC KEYBOARD WITH TOUCH ID — The comfortable-to-use, backlit Magic Keyboard comes with full-height function keys and Touch ID, which gives you a fast, easy, secure way to unlock your Mac and sign in to apps and sites — all at the touch of a finger.\nVERSATILE CONNECTIVITY — MacBook Air features a MagSafe charging port, two Thunderbolt ports, and a headphone jack.\nCOMES WITH APPLECARE WARRANTY — Every Mac comes with a one-year limited warranty and up to 90 days of complimentary technical support. Get AppleCare+ to extend your coverage.');

-- Insert additional sample products for 'Phone' category (category_id = 3)
INSERT INTO product (product_name, image_url, price_unit, sku, quantity, category_id, vendor_id,description)
VALUES
    ('IPhone 12 Pro', 'https://cdn.tgdd.vn/Files/2020/10/20/1300523/untitled1_800x450.png', 999.99, 'SKU12358', 50, 3, 3,'This device is locked to AT&T only and not compatible with any other carrier.\nPlease check with your carrier to verify compatibility.\nWhen you receive the phone, insert a SIM card from a compatible carrier. Then, turn it on, connect to Wi-Fi, and follow the on screen prompts to activate service.\nTested for battery health and guaranteed to have a minimum battery capacity of 80%.'),
    ('IPhone 13 Pro', 'https://media.idownloadblog.com/wp-content/uploads/2021/09/Apple-iPhone-13-Pro-advertisement.jpg', 999.99, 'SKU12359', 45, 3, 3,'6.1" Super Retina XDR display. 5G Superfast downloads, high?quality streaming\nCinematic mode in 1080p at 30 fps. Dolby Vision HDR video recording up to 4K at 60 fps. 2X Optical zoom range\nA15 Bionic chip. New 6-core CPU with 2 performance and 4 efficiency cores. New 4-core GPU. New 16-core Neural Engine\nUp to 19 hours video playback. Face ID. Ceramic Shield front. Aerospace-grade aluminum\nWater resistant to a depth of 6 meters for up to 30 minutes. Compatible with MagSafe accessories and wireless chargers'),
    ('IPhone 14', 'https://i.pinimg.com/736x/d0/81/8f/d0818ffe7f7978ce296b6e11257b7d7a.jpg', 899.99, 'SKU12360', 55, 3, 3,'Powered by the Snapdragon 8 Gen 2, the A14 ProMax delivers ultra-fast 5G speeds and smooth multitasking with 6GB/8GB RAM, perfect for streaming, gaming, and browsing without lag.\nCapture breathtaking photos with the 13MP front and 50MP rear cameras, ideal for high-resolution shots and clear video calls. Every moment is crisp, vibrant, and share-worthy.\nStay connected all day with the long-lasting 6800mAh battery. No more frequent charging—perfect for power users who need a reliable phone throughout the day.\nEnjoy an immersive viewing experience with the 6.8" HD screen, offering vivid colors and sharp clarity. Whether it''s gaming, watching videos, or reading, everything looks stunning.\nWith Face ID, fingerprint lock, and dual SIM support, your personal data stays secure while you enjoy the convenience of using two numbers on one device.'),
    ('IPhone SE', 'https://cdn.iphoneincanada.ca/wp-content/uploads/2022/03/iphone-se-2022-hero.jpg', 99.99, 'SKU12361', 60, 3, 3,'Factory unlocked iPhone and compatible with AT&T, T-Mobile, Mint, Us Mobile, Ting Mobile, Simple Mobile, Tello, Consumer Cellular etc - NOT COMPATIBLE with Verizon or Straight Talk\nReady out of the box, Phone included with generic box with a charger, cable, and handsfree\nInspected and guaranteed to have minimal to no cosmetic damage, which is not noticeable when the device is held at arms length. Successfully passed a full diagnostic test which ensures perfect functionality. Tested for battery health and guaranteed to have a minimum battery capacity of +90%\nThe Apple iPhone SE is the 1st Generation iPhone SE made in 2016 along with the iPhone 6s and iPhone 6s Plus. The iPhone SE has the same shape as the iPhone 5 and iPhone 5s, but is a lot more powerful. The iPhone 5 and 5s cases will also fit the iPhone SE and vice versa\nThis iPhone is able to update to the latest version of iOS 15\nConnector type: lightning'),
    ('IPhone 15 Pro Max', 'https://cafedidong.vn/wp-content/uploads/2024/03/%C4%90i%E1%BB%87n-tho%E1%BA%A1i-Apple-iphone-15-pro-kim-long-mobile-cafedidong-7.jpg', 1299.99, 'SKU12362', 35, 3, 3,'6.7inch Super Retina XDR display. ProMotion technology. Always-On display. Titanium with textured matte glass back. Action button\nDynamic Island. A magical way to interact with iPhone. A17 Pro chip with 6-core GPU\nPro camera system. 48MP Main | Ultra Wide| Telephoto. Super-high-resolution photos (24MP and 48MP). Next-generation portraits with Focus and Depth Control. Up to 10x optical zoom range\nEmergency SOS via satellite. Crash Detection. Roadside Assistance via satellite\nUp to 29 hours video playback. USB-C, Supports USB 3 for up to 20x faster transfers. Face ID'),
    ('Samsung Galaxy S21 Ultra SmartPhone', 'https://i.ytimg.com/vi/gwhRsOBQFvQ/maxresdefault.jpg', 699.99, 'SKU12363', 50, 3, 3,'6.7", 1080 x 2400 pixels, Dynamic AMOLED 2X, 120Hz, HDR10+, 1300nits, 4800mAh Battery\n128GB ROM, 8GB RAM, No SD Card Slot, Qualcomm SM8350 Snapdragon 888 5G (5 nm), Octa-Core, Adreno 660.\nRear Camera: 64MP, f/2.0 + 12MP, f/1.8 + 12MP, f/2.2, Front Camera: 10 MP, f/2.2, Android 11, One UI 3.1\n2G: GSM 850/900/1800/1900, CDMA 800/1900, 3G: HSDPA 850/900/1700(AWS)/1900/2100, CDMA2000 1xEV-DO, 4G LTE: 1/2/3/4/5/7/8/12/13/14/18/19/20/25/26/28/30/38/39/40/41/46/48/66/71, 5G: 2/5/25/41/66/71/260/261 SA/NSA/Sub6/mmWave - Single SIM\nUS Model w/ Warranty. Compatible with Most GSM and CDMA Carriers like T-Mobile, AT&T, MetroPCS, etc. Will Also work with CDMA Carriers Such as Verizon, Sprint'),
    ('Samsung Galaxy Note 20 SmartPhone', 'https://i.ytimg.com/vi/aS4lnURLvLo/maxresdefault.jpg', 999.99, 'SKU12364', 30, 3, 3,'Power of 5G: Get next-level power for everything you love to do with Samsung Galaxy 5G; Share more, game harder, experience more and never miss a beat\nSingle Take AI: Capture video and multiple types of images with one tap of the shutter button; Lenses, effects and filters capture the best of every moment, every time\nHi-Res Camera Zoom: Capture hi-res images as if you’re 3 feet away, from 100 feet away; Whether you want to zoom in close from afar or magnify details nearby, the new 30x Space Zoom gives you impressive power and clarity\nBright Night Mode: Capture crisp images and vibrant video in Bright Night mode and create high-quality content in low light – no flash needed\nSuper Fast Charging: Charge up quicker with Super Fast Charge so you can keep moving with more juice; Give your buds – or Galaxy buds – a boost of power with Wireless PowerShare right from Galaxy S20+ Plus 5G'),
    ('Samsung Galaxy Z Fold 3 SmartPhone', 'https://i.ytimg.com/vi/VTrMz9uBB34/maxresdefault.jpg', 1799.99, 'SKU12365', 25, 3, 3,'Expansive Screen: Get a super slim tablet right in your pocket with the ultimate folding mobile phone screen\nNear Invisible Camera: Enjoy an incredible uninterrupted view thanks to the first-ever Under Display Camera\n120Hz AMOLED 2X Screen: Everything looks brilliant on this big, beautiful, clear display offering a mesmerizing and dynamic viewing experience\nMultiple Windows: Get more done with three multi-windows that allow you to schedule, edit, and build presentations in a snap\nHyper Fast Speed: Live life in the fast lane with built-in 5G connectivity and hyper-fast processing power\nTwo Screens, Many Ways to Flex Them: Do more of what you love at the same time with Galaxy Flex Mode; Fold it at any angle and hold it any way you like\nCharged at the Speed of Life: Stay in charge, not beholden to your charger with 25W Super Fast Charging'),
    ('Samsung Galaxy A52 SmartPhone', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR30oRqhM4EL_aIxazdRzTGekEnNxsCS3pLyA&s', 499.99, 'SKU12366', 65, 3, 3,'6.5" Super AMOLED, 90Hz, 800 nits, 1080 x 2400 (FHD+), 4500mAh Battery, IP67 water and dust resistant, On-Screen Fingerprint\n128GB ROM, 6GB RAM, Qualcomm SM7125 Snapdragon 720G (8 nm), Octa-core, Adreno 618, Android 11, One UI 3.1\nRear Camera: 64MP, f/1.8 + 12MP, f/2.2 + 5MP, f/2.4 + 5MP, f/2.4, Front Camera: 32MP, f/2.2, Bluetooth 5.0\n2G GSM 850/900/S1800/1900, 3G UMTS B1(2100), B2(1900), B5(850), B8(900), 4G LTE B1(2100), B2(1900), B3(1800), B5(850), B7(2600), B8(900), B20(800), B28(700), B38(2600), B40(2300), B41(2500) - Dual SIM\nInternational Model - No Warranty in US. Compatible with Most GSM Carriers like T-Mobile, AT&T, MetroPCS, etc. Will NOT work with CDMA Carriers Such as Verizon, Sprint, Boost'),
    ('Samsung Galaxy S22 Ultra SmartPhone', 'https://mir-s3-cdn-cf.behance.net/project_modules/hd/b6e148147716775.62c743a58f7ca.jpg', 1199.99, 'SKU12367', 40, 3, 3,'6.6", 1080 x 2340pixels, Infinity-O FHD+ Dynamic AMOLED 2X Display, 4500mAh Battery, Wireless Powershare\n128GB ROM, 8GB RAM, No SD Card Slot, Qualcomm SM8450 Snapdragon 8 Gen 1 (4 nm), Octa-Core, Adreno 730\nRear Camera: 50MP, f/1.8 + 10MP, f/2.4 + 12MP, f/2.2, Front Camera: 10 MP, f/2.2, Android 12, One UI 4.1\n2G: GSM 850/900/1800/1900, CDMA 800/1900, 3G: HSDPA 850/900/1700(AWS)/1900/2100, CDMA2000 1xEV-DO, 4G LTE: 1/2/3/4/5/7/8/12/13/14/18/19/20/25/26/28/29/30/38/39/40/41/46/48/66/71, 5G: 1/3/5/7/8/20/28/38/41/66/71/260/261SA/NSA/Sub6/mmWave - Single SIM\nUS Model with a limited Warranty, which will be provided by the Manufacturer at their discretion. Terms and conditions apply. Compatible with Most GSM and CDMA Carriers like T-Mobile, AT&T, MetroPCS, etc. Will Also work with CDMA Carriers Such as Verizon, Sprint.');

-- Insert additional sample products for 'Book' category (category_id = 2)
INSERT INTO product (product_name, image_url, price_unit, sku, quantity, category_id, vendor_id,description)
VALUES
    ('Far from the Tree by Andrew Solomon book', 'https://i.ebayimg.com/images/g/aTIAAOSwNZlmnAgr/s-l1200.jpg', 14.99, 'SKU12368', 100, 2, 3,'National Book Critics Circle Award, Nonfiction, 2013\nFrom the National Book Award-winning author of the "brave...deeply humane...open-minded, critically informed, and poetic" (The New York Times) The Noonday Demon, comes a game-changer of a book about the impact of extreme personal and cultural difference between parents and children.\nA brilliant and utterly original thinker, Andrew Solomon''s journey began from his experience of being the gay child of straight parents. He wondered how other families accommodate children who have a variety of differences: families of people who are deaf, who are dwarfs, who have Down syndrome, who have autism, who have schizophrenia, who have multiple severe disabilities, who are prodigies, who commit crimes, who are transgender. Bookended with Solomon''s experiences as a son, and then later as a father, this book explores the old adage that says the apple doesn''t fall far from the tree; instead some apples fall a couple of orchards away, some on the other side of the world.\nIn 12 sharply observed and moving chapters, Solomon describes individuals who have been heartbreaking victims of intense prejudice, but also stories of parents who have embraced their childrens'' differences and tried to change the world''s understanding of their conditions. Solomon''s humanity, eloquence, and compassion give a voice to those people who are never heard. A riveting, powerful take on a major social issue, Far from the Tree offers far-reaching conclusions about new families, academia, and the way our culture addresses issues of illness and identity.'),
    ('The Noonday Demon by Andrew Solomon book', 'https://pbs.twimg.com/media/E6RfBu-XIAMTyhy.jpg', 19.99, 'SKU12369', 85, 2, 3,'National Book Award, Nonfiction, 2001\nWith uncommon humanity, candor, wit, and erudition, National Book Award winner Andrew Solomon takes the listener on a journey of incomparable range and resonance into the most pervasive of family secrets.\nThe Noonday Demon examines depression in personal, cultural, and scientific terms. Drawing on his own struggles with the illness and interviews with fellow sufferers, doctors and scientists, policymakers and politicians, drug designers and philosophers, Solomon reveals the subtle complexities and sheer agony of the disease. He confronts the challenge of defining the illness and describes the vast range of available medications, the efficacy of alternative treatments, and the impact the malady has had on various demographic populations around the world and throughout history. He also explores the thorny patch of moral and ethical questions posed by emerging biological explanations for mental illness.\nThe depth of human experience Solomon chronicles, the range of his intelligence, and his boundless curiosity and compassion will change the listener''s view of the world.'),
    ('Software Engineering by Ian Sommerville book', 'https://i.ebayimg.com/images/g/6WgAAOSwEudgjpQb/s-l640.jpg', 79.99, 'SKU12370', 55, 2, 3,'For courses in computer science and software engineering\nThe Fundamental Practice of Software Engineering\nSoftware Engineering introduces readers to the overwhelmingly important subject of software programming and development. In the past few years, computer systems have come to dominate not just our technological growth, but the foundations of our world’s major industries. This text seeks to lay out the fundamental concepts of this huge and continually growing subject area in a clear and comprehensive manner.\nThe Tenth Edition contains new information that highlights various technological updates of recent years, providing readers with highly relevant and current information. Sommerville’s experience in system dependability and systems engineering guides the text through a traditional plan-based approach that incorporates some novel agile methods. The text strives to teach the innovators of tomorrow how to create software that will make our world a better, safer, and more advanced place to live.'),
    ('Clean Code by Robert C. Martin book', 'https://m.media-amazon.com/images/I/71T7aD3EOTL._UF1000,1000_QL80_.jpg', 39.99, 'SKU12371', 75, 2, 3,'Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way.\nNoted software expert Robert C. Martin, presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship. Martin, who has helped bring agile principles from a practitioner’s point of view to tens of thousands of programmers, has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of software craftsman, and make you a better programmer―but only if you work at it.\nWhat kind of work will you be doing? You’ll be reading code―lots of code. And you will be challenged to think about what’s right about that code, and what’s wrong with it. More importantly you will be challenged to reassess your professional values and your commitment to your craft.'),
    ('Design Patterns by Erich Gamma book', 'https://m.media-amazon.com/images/I/81IGFC6oFmL._AC_UF1000,1000_QL80_.jpg', 49.99, 'SKU12372', 90, 2, 3,'Capturing a wealth of experience about the design of object-oriented software, four top-notch designers present a catalog of simple and succinct solutions to commonly occurring design problems. Previously undocumented, these 23 patterns allow designers to create more flexible, elegant, and ultimately reusable designs without having to rediscover the design solutions themselves.\nThe authors begin by describing what patterns are and how they can help you design object-oriented software. They then go on to systematically name, explain, evaluate, and catalog recurring designs in object-oriented systems. With Design Patterns as your guide, you will learn how these important patterns fit into the software development process, and how you can leverage them to solve your own design problems most efficiently.\nEach pattern describes the circumstances in which it is applicable, when it can be applied in view of other design constraints, and the consequences and trade-offs of using the pattern within a larger design. All patterns are compiled from real systems and are based on real-world examples. Each pattern also includes code that demonstrates how it may be implemented in object-oriented programming languages like C++ or Smalltalk.'),
    ('Algorithms by Robert Sedgewick book', 'https://media.karousell.com/media/photos/products/2020/12/8/algorithm_4th_edition_by_rober_1607417158_01c9ba49_progressive.jpg', 59.99, 'SKU12373', 70, 2, 3,'This fourth edition of Robert Sedgewick and Kevin Wayne’s Algorithms is the leading textbook on algorithms today and is widely used in colleges and universities worldwide. This book surveys the most important computer algorithms currently in use and provides a full treatment of data structures and algorithms for sorting, searching, graph processing, and string processing--including fifty algorithms every programmer should know. In this edition, new Java implementations are written in an accessible modular programming style, where all of the code is exposed to the reader and ready to use.\nThe algorithms in this book represent a body of knowledge developed over the last 50 years that has become indispensable, not just for professional programmers and computer science students but for any student with interests in science, mathematics, and engineering, not to mention students who use computation in the liberal arts.\nThe companion web site, algs4.cs.princeton.edu, contains\nAn online synopsis\nFull Java implementations\nTest data\nExercises and answers\nDynamic visualizations\nLecture slides\nProgramming assignments with checklists\nLinks to related material\nThe MOOC related to this book is accessible via the "Online Course" link at algs4.cs.princeton.edu. The course offers more than 100 video lecture segments that are integrated with the text, extensive online assessments, and the large-scale discussion forums that have proven so valuable. Offered each fall and spring, this course regularly attracts tens of thousands of registrants.\nRobert Sedgewick and Kevin Wayne are developing a modern approach to disseminating knowledge that fully embraces technology, enabling people all around the world to discover new ways of learning and teaching. By integrating their textbook, online content, and MOOC, all at the state of the art, they have built a unique resource that greatly expands the breadth and depth of the educational experience.'),
    ('The Mythical Man-Month by Fred Brooks book', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348430512i/13629.jpg', 29.99, 'SKU12374', 80, 2, 3,'Few books on software project management have been as influential and timeless as The Mythical Man-Month. With a blend of software engineering facts and thought-provoking opinions, Fred Brooks offers insight for anyone managing complex projects. These essays draw from his experience as project manager for the IBM System/360 computer family and then for OS/360, its massive software system. Now, 20 years after the initial publication of his book, Brooks has revisited his original ideas and added new thoughts and advice, both for readers already familiar with his work and for readers discovering it for the first time.\nThe added chapters contain (1) a crisp condensation of all the propositions asserted in the original book, including Brooks'' central argument in The Mythical Man-Month: that large programming projects suffer management problems different from small ones due to the division of labor; that the conceptual integrity of the product is therefore critical; and that it is difficult but possible to achieve this unity; (2) Brooks'' view of these propositions a generation later; (3) a reprint of his classic 1986 paper "No Silver Bullet"; and (4) today''s thoughts on the 1986 assertion, "There will be no silver bullet within ten years."'),
    ('Artificial Intelligence by Stuart Russell book', 'https://cdn.prod.website-files.com/64afb137c52becee3aca95ce/64b439948883c0cbf9da3807_640f3401d7f0586af8fffb13_Russell-AI.jpeg', 89.99, 'SKU12375', 60, 2, 3,'Thelong-anticipated revision of ArtificialIntelligence: A Modern Approach explores the full breadth and depth of the field of artificialintelligence (AI). The 4th Edition brings readers up to date on the latest technologies,presents concepts in a more unified manner, and offers new or expanded coverageof machine learning, deep learning, transfer learning, multi agent systems,robotics, natural language processing, causality, probabilistic programming,privacy, fairness, and safe AI.'),
    ('Introduction to the Theory of Computation by Michael Sipser book', 'https://m.media-amazon.com/images/I/61dPNb6AUJL._AC_UF1000,1000_QL80_.jpg', 69.99, 'SKU12376', 50, 2, 3,'Gain a clear understanding of even the most complex, highly theoretical computational theory topics in the approachable presentation found only in the market-leading INTRODUCTION TO THE THEORY OF COMPUTATION, 3E. The number one choice for today''s computational theory course, this revision continues the book''s well-know, approachable style with timely revisions, additional practice, and more memorable examples in key areas. A new first-of-its-kind theoretical treatment of deterministic context-free languages is ideal for a better understanding of parsing and LR(k) grammars. You gain a solid understanding of the fundamental mathematical properties of computer hardware, software, and applications with a blend of practical and philosophical coverage and mathematical treatments, including advanced theorems and proofs. INTRODUCTION TO THE THEORY OF COMPUTATION, 3E''s comprehensive coverage makes this a valuable reference for your continued studies in theoretical computing.'),
    ('The Pragmatic Programmer by Andrew Hunt book', 'https://is1-ssl.mzstatic.com/image/thumb/Publication123/v4/11/19/d1/1119d1d7-1665-0ef0-bf24-92487b9c1527/9780135956915.jpg/1200x1200wz.jpg', 44.99, 'SKU12377', 65, 2, 3,'The Pragmatic Programmer by Andrew Hunt');